swagger: '2.0'
info:
  version: 0.0.1
  title: diskinfo
  description: >-
    A simple service to get diskinfo as an example of using swagger -2.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
host: 'localhost:8080'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /disk:
    get:
      description: Returns disk information of the hosting server
      produces:
        - application/json
      responses:
        '200':
          description: DISK info
          schema:
            $ref: '#/definitions/DISK'
definitions:
  DISK:
    type: object
    required:
      - total
      - free
    properties:
      total:
        type: string
      free:
        type: string
